export const timelineElements = [
    {
        id: 0,
        title: "App/Cloud Support Senior Analyst",
        location: "Accenture - Mandaluyong, Metro Manila",
        description: "Servicenow with CSA Certification and multiple micro-certification",
        date: "August 2024 - ",
        icon: "work",
    },
    {
        id: 1,
        title: "Software Developer",
        location: "Smartfox Data Solutions, Inc. - Osmeña Avenue, Quezon City",
        description: "Web developer with a focus on Laravel + LAMP working on CRM content and other projects.",
        date: "October 2023 - August 2024",
        icon: "work",
    },
    {
        id: 2,
        title: "Technology Consultant I",
        location: "DXC Technology - Taguig, Metro Manila",
        description: "Web developer mainly working on PHP projects with RDBMS.",
        date: "March 2022 - July 2023",
        icon: "work",
    },
    {
        id: 3,
        title: "Intern",
        location: "Lyceum of the Philippines University - General Trias, Cavite",
        description: "Front-end Developer focused on UI and overall design for a web application.",
        date: "February 2021 - July 2021",
        icon: "work",
    },
    {
        id: 4,
        title: "Bachelor's Degree in Information Technology",
        location: "Lyceum of the Philippines University - General Trias, Cavite",
        description: "Graduated with a primary focus on Java and mobile development.",
        date: "2016-2021",
        icon: "school",
    },
];